#!/usr/bin/env python3
"""Generate native/harness/symbols.h from the checksum pipeline's symbol map
(Common Library/Checksum/EquMain.asm), which is regenerated on every ROM build."""
import re, sys, os

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(PROJ, "Common Library", "Checksum", "EquMain.asm")
DST = os.path.join(PROJ, "native", "harness", "symbols.h")

KEEP = re.compile(r"^(TeamData_|TeamDataPtrTable|TeamOverallRatings|SRAM_|SaveBuf_"
                  r"|Menu|R_|RunGame|StartGame|CalcChecksum|VBlankInt|Z80_)")

lines = ["/* Generated by native/gen-symbols.py from EquMain.asm — do not edit. */",
         "#ifndef _NHL94_SYMBOLS_H_", "#define _NHL94_SYMBOLS_H_", ""]
n = 0
for line in open(SRC, encoding="latin-1"):
    m = re.match(r"^(\w+) = \$([0-9A-Fa-f]+)", line)
    if m and KEEP.match(m.group(1)):
        lines.append(f"#define SYM_{m.group(1)} 0x{m.group(2).upper()}")
        n += 1
lines += ["", "#endif", ""]
open(DST, "w").write("\n".join(lines))
print(f"symbols.h: {n} symbols")
