/* Generated by native/gen-symbols.py from EquMain.asm — do not edit. */
#ifndef _NHL94_SYMBOLS_H_
#define _NHL94_SYMBOLS_H_

#define SYM_R_StackSP 0xFFFFF6
#define SYM_R_CrowdPeak 0xFFC314
#define SYM_R_GoalsHome 0xFFC6DA
#define SYM_R_ShotsHome 0xFFC6CE
#define SYM_R_GoalsAway 0xFFCA3E
#define SYM_R_ShotsAway 0xFFCA32
#define SYM_R_SaveBuffer 0xFF0000
#define SYM_R_SaveBadFlag 0xFFD458
#define SYM_R_MenuSelections 0xFFD048
#define SYM_StartGame 0x2FA
#define SYM_TeamDataPtrTable 0x30A
#define SYM_TeamData_ASE 0x37E
#define SYM_TeamData_ASW 0x674
#define SYM_TeamData_BOS 0x966
#define SYM_TeamData_BUF 0xC4C
#define SYM_TeamData_CGY 0xF3A
#define SYM_TeamData_CHI 0x1234
#define SYM_TeamData_DET 0x152E
#define SYM_TeamData_EDM 0x1848
#define SYM_TeamData_HFD 0x1B44
#define SYM_TeamData_LA 0x1E52
#define SYM_TeamData_DAL 0x214E
#define SYM_TeamData_MTL 0x243E
#define SYM_TeamData_NJ 0x2740
#define SYM_TeamData_NYI 0x2A58
#define SYM_TeamData_NYR 0x2D5C
#define SYM_TeamData_OTW 0x3054
#define SYM_TeamData_PHI 0x3348
#define SYM_TeamData_PIT 0x3646
#define SYM_TeamData_QUE 0x393C
#define SYM_TeamData_SJ 0x3C42
#define SYM_TeamData_STL 0x3F30
#define SYM_TeamData_TB 0x4216
#define SYM_TeamData_TOR 0x4518
#define SYM_TeamData_VAN 0x481C
#define SYM_TeamData_WPG 0x4B0A
#define SYM_TeamData_WSH 0x4DFC
#define SYM_TeamData_FLA 0x50E6
#define SYM_TeamData_ANH 0x5330
#define SYM_VBlankInt 0x76B2
#define SYM_RunGame 0x76B8
#define SYM_SRAM_InitAndLoadSave 0x1A050
#define SYM_SaveBuf_VerifyChecksum 0x1A14E
#define SYM_SRAM_FormatSave 0x1A19C
#define SYM_SRAM_WriteBytes 0x1A1E4
#define SYM_SRAM_RecalcChecksum 0x1A206
#define SYM_SRAM_ReadBytes 0x1A244
#define SYM_Z80_MuteAllFM 0x1A264
#define SYM_Z80_WriteVolume 0x1A574
#define SYM_Z80_ClearFlagUnknown 0x1A66E
#define SYM_Z80_LoadROM 0x1ACC2
#define SYM_Menu_DrawOptionValue 0xF7B66
#define SYM_MenuText_NA 0xF7CEE
#define SYM_MenuOptionLists 0xF7D04
#define SYM_MenuText_PeriodLength 0xF7F3C
#define SYM_TeamOverallRatings 0xFE18E
#define SYM_CalcChecksum 0xFFAC0

#endif
